baseURL = "https://yaesolkim.github.io/"
languageCode = "en-us"
title = "Yaesol Kim"
theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/yaesolKim/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/yaesolkim/"}
  ]

[params]
  description = "Ph. D Studetn"
